name: Smart Flutter Devlog with Random Contributions

on:
  schedule:
    - cron: '0 2 * * *' # Runs daily at 2 AM UTC
  workflow_dispatch:

jobs:
  smart-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Decide whether to commit today
        id: randomizer
        run: |
          DAYS_TO_COMMIT=5
          TODAY=$(date +%u)
          SELECTED_DAYS=$(shuf -e 1 2 3 4 5 6 7 | head -n $DAYS_TO_COMMIT)
          echo "Selected days: $SELECTED_DAYS"
          if echo "$SELECTED_DAYS" | grep -q "$TODAY"; then
            echo "commit_today=true" >> $GITHUB_OUTPUT
          else
            echo "commit_today=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate random number of commits
        if: steps.randomizer.outputs.commit_today == 'true'
        id: commit_count
        run: |
          COUNT=$(( (RANDOM % 3) + 1 )) # 1 to 3 commits
          echo "commit_count=$COUNT" >> $GITHUB_OUTPUT

      - name: Make multiple commits
        if: steps.randomizer.outputs.commit_today == 'true'
        run: |
          for i in $(seq 1 ${{ steps.commit_count.outputs.commit_count }}); do
            GOAL=$(jq -r '.[randrange(length)]' data/flutter_goals.json)
            echo "🕓 $(date '+%Y-%m-%d %H:%M:%S') — $GOAL" >> devlog.txt
            git config --global user.name "ab"
            git config --global user.email "abrhamgetachew99@gmail.com"
            git add devlog.txt
            git commit -m "🛠️ Flutter log #$i: $(date '+%Y-%m-%d')"
          done
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
